import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Bruno's Resume",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <ul>
            <Link href="/">Home</Link>
            <Link href="/about">about</Link>
          </ul>
        </header>
        <div className="container mx-auto">{children}</div>
      </body>
    </html>
  )
}
