export const jobPositions = [
  {
    id: 1,
    title: 'Senior React Engineer',
    company: 'Givebutter',
    location: 'Remote, United States',
    startDate: 'August 2023',
    endDate: 'October 2022',
    description:
      'Develop and maintain auctions and internal user operations Utilize Javascript, TypeScript, React, and React Query for feature implementation. Successfully delivered impactful features, enhancing fundraising efforts.Optimized internal user operations, boosting productivity.',
    responsibilities: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.',
    ],
    skills: ['Tailwind CSS', 'TypeScript', 'docker', 'react', 'REST APIs', 'React', 'JavaScript', 'Git', 'HTML'],
  },
  {
    id: 2,
    title: 'Senior Frontend Developer',
    company: 'Lettuce Grow',
    location: 'Remote, United States',
    startDate: 'May 2021',
    endDate: 'August 2022',
    description:
      'Senior Frontend Developer working with Gatsby, React, React Native, Redux, Tailwind, and Jest for an outsource client from US. Worked on systems responsible for dealing with internal operations and consumer-facing, such as inventory and orders management, developing the client E-commerce solution and mobile app',
    responsibilities: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.',
    ],
    skills: [
      'Tailwind CSS',
      'docker',
      'react',
      'REST APIs',
      'React Native',
      'GatsbyJS',
      'Redux.js',
      'React.js',
      'JavaScript',
      'Git',
      'HTML',
    ],
  },
  {
    id: 3,
    title: 'Contractor Full-Stack Developer',
    company: 'Ubistart',
    location: 'Remote, Brazil',
    startDate: 'March 2021',
    endDate: 'May 2021',
    description:
      'Full-stack Developer working with WordPress, React, and PHP. Worked as a contractor responsible for integrating React into WordPress for an EdTech client. My main responsibilities included fully integrating React with WordPress REST API service while expanding its functionalities.',
    responsibilities: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatibus.',
    ],
    skills: ['docker', 'WordPress', 'react', 'PHP', 'MySQL', 'REST APIs', 'React.js', 'JavaScript', 'Git', 'HTML', 'SQL'],
  },
]
